### ISSUE TITLE
Game Over Screen

### ISSUE THREAD

**Issue by umutatakul** [ms0g/breakout#1]
Maybe you could add a  screen about for game over on the end of the game.
![image](https://github.com/ms0g/breakout/assets/60206202/8151a86b-4d5e-47c4-9b4f-00ac2eaa4990)

**Comment by tanmay-devv** [comment]
let me try that.

**Comment by xms0g** [comment]
<img width="636" alt="Screenshot 2024-02-24 at 21 17 25" src="https://github.com/ms0g/breakout/assets/2058327/3af256b3-8adb-43cf-8038-3706b9d85ff5">
