### ISSUE TITLE
Business Logic Error

### ISSUE THREAD

**Issue by umutatakul** [ms0g/breakout#2]
### The ball touched approximately the marked area

![WhatsApp Görsel 2024-02-12 saat 05 19 53_f9d61cb4](https://github.com/ms0g/breakout/assets/60206202/45830feb-7561-4175-acd7-8939dc7084b1)

**Comment by xms0g** [comment]
This is not bug. After first 2 rows, hit counts of bricks increase as 2,3,4.

**Comment by umutatakul** [comment]
Oh okay. Thx for information.
