### ISSUE TITLE
Game Freezing and Drop Lives

### ISSUE THREAD

**Issue by umutatakul** [ms0g/breakout#3]
![WhatsApp Görsel 2024-02-12 saat 22 18 46_03bb5f98](https://github.com/ms0g/breakout/assets/60206202/af9225e8-6565-452f-a33d-9a7ee7913b0d)

### On our friend @engincalimfidan 's computer, I directly reduce the last lives to 1 and the game freezes.

**Comment by xms0g** [comment]
Cannot reproduce. Seems it's related to DosBox configuration.
