### ISSUE TITLE
How to Debug

### ISSUE THREAD

**Issue by nbarkhina** [ms0g/breakout#4]
Very cool project. Question I have is after installing Turbo C++ I am able to compile it with make and also with the Turbo editor by creating a project. However I am not able to debug it. I am able to set a breakpoint in vga where it tries to create the offscreen buffer but that code fails (only when debugging) were you able to get around this issue? Would be nice to actually step through the code as it's running to see how it works.

Thanks

**Comment by xms0g** [comment]
Nope. Haven't used debugger before. May be related to DOSBox, which we don't know how it manages heap memory. I may noodle it for a while.
Let me know you figure it out.

**Comment by nbarkhina** [comment]
Ok I figured it out - if you go into the Debugger options Turbo C++ starts with only 64k for the heap. If you increase to like 200k now the application debugs fine.

![image](https://github.com/ms0g/breakout/assets/10982154/a3763fe7-dfcf-4796-b393-07f13402b605)

**Comment by xms0g** [comment]
Ah, makes sense. Far pointer points to addresses beyond the default segment that is already 64kb. Good job.
